services:
  - type: web
    name: interview-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: GEMINI_API_KEY
        value: your_gemini_key
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: http://localhost:5173